#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ios
version:      0.0.1
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
