#!./perl

$|=1;
use open ":std", ":encoding(UTF-8)";
use IO::Handle;
STDOUT->autoflush(1);
use strict;
use warnings;
use Config;
use Cwd qw/getcwd/;
use TAP::Parser::Iterator::iOS;
use TAP::Parser::SourceHandler::iOSExecutable;
use TAP::Parser::SourceHandler::iOSPerl;

BEGIN {
    *CORE::GLOBAL::exit = sub {
        $::ios_harness_status = shift // 0;
    };
}

$ENV{LC_ALL} = 'C';
$ENV{LC_CTYPE} = 'C';
$ENV{PERL_TEST_ABORT_FIRST_FAILURE} = 0;
$ENV{HOME} = getcwd();
# $ENV{PERL_TEST_TIME_OUT_FACTOR} = 15;
# $ENV{PERL_SKIP_PSYCHO_TEST} = 1;
# $ENV{PERL_BENCHMARK} = 1;
# $ENV{PERL_TEST_MEMORY} = 1;
# $ENV{PERL_TEST_HARNESS_ASAP} = 1;
# $ENV{PERL_USE_UNSAFE_INC}
# $ENV{PERL_DEBUG_FULL_TEST}
# TODO: on iOS these tests may 
# hang, crash or exit unexpectedly,
# or may pass, causing havoc afterwards,
# or they may pass or fail randomly
my @ios_blacklist;

# Device: Test::Harness depends on child-process, taint, and exit-status
# behavior that is not yet adapted to the embedded iOS runner. Revisit after
# integrating the corresponding upstream-compatible behavior.
push @ios_blacklist, '../cpan/Test-Harness/';

# Simulator: these switch/debug tests are known to fail on x86_64 even
# though they pass on the arm64 device.
my @simul_blacklist = qw(
    run/switches.t
    run/switchd.t
    run/switchM.t
);

# Simulator: command-line switch behavior differs on the x86_64 target.
push @simul_blacklist, qw(
    cmd/switch.t
);

# Simulator: argv behavior differs from the device harness.
push @simul_blacklist, qw(
    io/argv.t
);

# Simulator: these numeric, packing, stat, and vector cases have known
# x86_64 results that differ from the arm64 device.
push @simul_blacklist, qw(
    op/64bitint.t
    op/blocks.t
    op/coreamp.t
    op/pack.t
    op/sprintf2.t
    op/stat.t
    op/vec.t
);

# Simulator: porting tests inspect host/build details unavailable or
# intentionally different in the simulator build.
push @simul_blacklist, qw(
    porting/checkcase.t
    porting/checkcfgvar.t
    porting/checkcfgvar.t
    porting/cmp_version.t
    porting/diag.t

    porting/manifest.t
    porting/pending-author.t
    porting/perlfunc.t
    porting/podcheck.t

    porting/readme.t
    porting/regen.t
    porting/utils.t
);

# Simulator: these distribution and extension tests have known x86_64
# failures and remain covered on the arm64 device where applicable.
push @simul_blacklist, qw(
    ../cpan/Archive-Tar/t/02_methods.t
    ../cpan/Archive-Tar/t/04_resolved_issues.t

    ../cpan/Filter-Util-Call/t/call.t

    ../cpan/Scalar-List-Utils/t/uniqnum.t

    ../dist/PathTools/t/cwd.t
    ../dist/PathTools/t/abs2rel.t
    ../dist/PathTools/t/taint.t

    ../dist/Carp/t/stack_after_err.t

    ../dist/Storable/t/file_magic.t
    ../dist/Storable/t/malice.t

    ../dist/threads/t/kill3.t

    ../ext/File-Find/t/taint.t
    ../ext/File-Glob/t/basic.t
    ../ext/File-Glob/t/threads.t

    ../lib/perl5db.t
);

sub dump_list {
    my @tests = @_;
    foreach my $t(@tests) {
        print "$t\n";
    }
}

sub exclude_tests {
    my @tests = @_;
    for my $black_list (@ios_blacklist)
    {
        for (my $index = 0; $index < scalar @tests;  $index ++)
        {
            if ($tests[$index] =~ m!$black_list!)
            {
                print "# iOS: excluding test: $tests[$index]\n";
                splice(@tests, $index, 1);
            }
        }
    }

    if ($Config{archname} =~ /x86_64/) {
        print "# NOTE: the following tests pass on device but fail on simulator. #TODO\n";
        for my $simul_black_list (@simul_blacklist)
        {
            for (my $index = 0; $index < scalar @tests;  $index ++)
            {
                if ($tests[$index] =~ m!$simul_black_list!)
                {
                    print "# iOS: excluding test: $tests[$index]\n";
                    splice(@tests, $index, 1);
                }
            }
        }
        # Simulator: Pod::Html and Pod::Simple are not stable in this target.
        @tests = grep(/^(?:(?!\.\.\/ext\/Pod\-Html))/, @tests);
        @tests = grep(/^(?:(?!\.\.\/cpan\/Pod\-Simple))/, @tests);
    }

    # Device: these suites require external commands or IPC mechanisms that
    # are unavailable without fork, pipes, or SysV IPC on iOS.
    @tests = grep(/^(?:(?!\.\.\/cpan\/IPC-Cmd))/, @tests);
    @tests = grep(/^(?:(?!\.\.\/cpan\/IPC-SysV))/, @tests);
    @tests = grep(/^(?:(?!\.\.\/ext\/IPC-Open3))/, @tests);

    # Device: these tests require make and the MakeMaker toolchain, which are
    # not available in the device Documents/runtime environment.
    @tests = grep(/^(?:(?!\.\.\/cpan\/ExtUtils-MakeMaker))/, @tests);
};

# @ARGV = ('base/cond.t');

do './harness';

CORE::exit($::ios_harness_status // 0);