#!./perl

$|=1;
use open ":std", ":encoding(UTF-8)";
use IO::Handle;
STDOUT->autoflush(1);
use strict;
use warnings;
use Config;
use Cwd qw/getcwd/;
use JSON::PP;

use ios;
use TAP::Parser::Iterator::iOS;
use TAP::Parser::SourceHandler::iOSExecutable;
use TAP::Parser::SourceHandler::iOSPerl;

BEGIN {
    *CORE::GLOBAL::exit = sub {
        $::ios_harness_status = shift // 0;
    };
}

$ENV{LC_ALL} = 'C';
$ENV{LC_CTYPE} = 'C';
$ENV{PERL_TEST_ABORT_FIRST_FAILURE} = 0;
$ENV{HOME} = getcwd();
# $ENV{PERL_TEST_TIME_OUT_FACTOR} = 15;
# $ENV{PERL_SKIP_PSYCHO_TEST} = 1;
# $ENV{PERL_BENCHMARK} = 1;
# $ENV{PERL_TEST_MEMORY} = 1;
# $ENV{PERL_TEST_HARNESS_ASAP} = 1;
# $ENV{PERL_USE_UNSAFE_INC}
# $ENV{PERL_DEBUG_FULL_TEST}
# TODO: on iOS these tests may 
# hang, crash or exit unexpectedly,
# or may pass, causing havoc afterwards,
# or they may pass or fail randomly

my @ios_blacklist = qw(
    ../ext/CamelBones-1.3.0/t/13-Exceptions.t
    ../ext/CamelBones-1.3.0/t/14-Threads.t
);

my @simul_blacklist = qw(
    ../ext/CamelBones-1.3.0/t/13-Exceptions.t
    ../ext/CamelBones-1.3.0/t/14-Threads.t
);

sub dump_list {
    my @tests = @_;
    foreach my $t(@tests) {
        print "$t\n";
    }
}

sub exclude_tests {
    my @tests = @_;
    for my $black_list (@ios_blacklist)
    {
        for (my $index = 0; $index < scalar @tests;  $index ++)
        {
            if ($tests[$index] =~ m!$black_list!)
            {
                print "# iOS: excluding test: $tests[$index]\n";
                splice(@tests, $index, 1);
            }
        }
    }

    if (($Config{ios_sdk} // '') =~ /simulator/) {
        print "# NOTE: the following tests pass on device but fail on simulator. #TODO\n";
        for my $simul_black_list (@simul_blacklist)
        {
            for (my $index = 0; $index < scalar @tests;  $index ++)
            {
                if ($tests[$index] =~ m!$simul_black_list!)
                {
                    print "# iOS: excluding test: $tests[$index]\n";
                    splice(@tests, $index, 1);
                }
            }
        }
    }

    my @excluded = (
        qr!\.\./cpan/IPC-Cmd!,
        qr!\.\./cpan/IPC-SysV!,
        qr!\.\./ext/IPC-Open3!,
        qr!\.\./cpan/Test-Harness!,
        qr!\.\./cpan/ExtUtils-MakeMaker!,
    );
    for my $pattern (@excluded) {
        my @kept;
        for my $test (@tests) {
            if ($test =~ $pattern) {
                print "# iOS: excluding test: $test\n";
            } else {
                push @kept, $test;
            }
        }
        @tests = @kept;
    }
    return @tests;
};

if (!grep { $_ !~ /^-/ } @ARGV) {
    $::do_nothing = $::do_nothing = 1;
    require './TEST';

    my @tests;
    for my $directory (qw(base comp run cmd io re opbasic op uni mro lib porting perf)) {
        @ARGV = ();
        _find_tests($directory);
        push @tests, @ARGV;
    }

    my ($extensions, $known_extensions);
    open(my $config, '<', '../config.sh') or die "Cannot open ../config.sh: $!";
    while (my $line = <$config>) {
        $extensions = $1 if $line =~ /^extensions=['"](.*)['"]$/;
        $known_extensions = $1 if $line =~ /^known_extensions=['"](.*)['"]$/;
    }
    close($config);
    push @tests, _tests_from_manifest($extensions, $known_extensions);

    @ARGV = grep { /^-/ } @ARGV;
    push @ARGV, exclude_tests(@tests);
}


do './harness';

CORE::exit($::ios_harness_status // 0);
