#!./perl
$|=1;
use open ":std", ":encoding(UTF-8)";
use strict;
use warnings;
use Config;

$ENV{LC_ALL} = 'C';
$ENV{LC_CTYPE} = 'C';
$ENV{PERL_TEST_ABORT_FIRST_FAILURE} = 0;
$ENV{PERL_TEST_TIME_OUT_FACTOR} = 15;
# $ENV{PERL_SKIP_PSYCHO_TEST} = 1;
# $ENV{PERL_BENCHMARK} = 1;
# $ENV{PERL_TEST_MEMORY} = 1;
# $ENV{PERL_TEST_HARNESS_ASAP} = 1;
# $ENV{PERL_USE_UNSAFE_INC}

my @ios_blacklist = (
    # on iOS these tests may either:
    # hang, crash or exit unexpectedly,
    # or may pass, causing havoc afterwards,
    # or they may pass or hang/crash indistinctly

    'io/openpid.t',
    'io/closepid.t',

    # pass, fail randomly
    're/pat_advanced.t',
    're/pat_advanced_thr.t',

    # DB_File not built in
    '../cpan/DB_File/t/db-threads.t',
    '../cpan/DB_File/t/db-recno.t',
    '../cpan/DB_File/t/db-hash.t',
    '../cpan/DB_File/t/db-btree.t',

    # hangs
    '../cpan/File-Temp/t/lock.t',

    # TODO
    '../cpan/IPC-SysV/t/ipcsysv.t',
    '../cpan/IPC-SysV/t/msg.t',
    '../cpan/IPC-SysV/t/pod.t',
    '../cpan/IPC-SysV/t/podcov.t',
    '../cpan/IPC-SysV/t/sem.t',
    '../cpan/IPC-SysV/t/shm.t',

    # no exec
    '../cpan/autodie/t/exec.t',

    # no command running on iOS
    '../cpan/IPC-Cmd/t/01_IPC-Cmd.t',
    '../cpan/IPC-Cmd/t/02_Interactive.t',
    '../cpan/IPC-Cmd/t/03_run-forked.t',

    # TODO test after proper subclassing of Iterator::Array
    '../cpan/Test-Harness/t/compat/inc-propagation.t',
    '../cpan/Test-Harness/t/compat/inc_taint.t',
    '../cpan/Test-Harness/t/compat/test-harness-compat.t',
    '../cpan/Test-Harness/t/compat/regression.t',
    '../cpan/Test-Harness/t/regression.t',

    # no backticks
    '../cpan/Pod-Usage/t/pod/selectsections.t',
    '../cpan/Pod-Usage/t/pod/headwithmarkup.t',
    '../cpan/Pod-Usage/t/pod/selectheaders.t',

    # no backticks
    '../dist/IO/t/io_dup.t',

    # TODO
    'io/perlio_leaks.t',

    '../dist/Time-HiRes/t/ualarm.t',

    '../ext/Devel-Peek/t/Peek.t',

    '../ext/DynaLoader/t/DynaLoader.t',
    '../ext/POSIX/t/posix.t',
    '../ext/POSIX/t/sigaction.t',
    '../ext/POSIX/t/wrappers.t',

    '../ext/IPC-Open3/t/fd.t',
    '../ext/IPC-Open3/t/IPC-Open2.t',
    '../ext/IPC-Open3/t/IPC-Open3.t',

    '../ext/XS-APItest/t/clone-with-stack.t',

    '../lib/feature/unicode_strings.t',
    
    '../dist/I18N-LangTags/t/80_all_env.t',
);

my @simul_blacklist = (
    'io/argv.t',
    'io/fflush.t',
    'io/defout.t',
    'io/inplace.t',

    'run/switches.t',
    'run/switchd.t',
        'run/switchM.t',
    'cmd/switch.t',

    'op/do.t',
    'op/64bitint.t',
    #'op/chr.t'
    'op/chdir.t',
    'op/heredoc.t',
    'op/pack.t',
    'op/sprintf2.t',
    'op/stat.t',
    'op/vec.t',
    
    'porting/checkcase.t',
    'porting/checkcfgvar.t',
    'porting/checkcfgvar.t',
    'porting/cmp_version.t',
    'porting/diag.t',

    'porting/manifest.t',
    'porting/pending-author.t',
    'porting/perlfunc.t',
    'porting/podcheck.t',
    
    'porting/readme.t',
    'porting/regen.t', 
    'porting/utils.t',

    '../cpan/Archive-Tar/t/02_methods.t',
    '../cpan/Archive-Tar/t/04_resolved_issues.t',
    '../cpan/Filter-Util-Call/t/call.t',
    '../cpan/Pod-Simple/t/htmlbat.t',

    '../cpan/Pod-Simple/t/search10.t',
    '../cpan/Pod-Simple/t/search12.t',
    '../cpan/Pod-Simple/t/search20.t',
    '../cpan/Pod-Simple/t/search22.t',
    '../cpan/Pod-Simple/t/search25.t',
    '../cpan/Pod-Simple/t/search26.t',
    '../cpan/Pod-Simple/t/search27.t',
    '../cpan/Pod-Simple/t/search28.t',
    '../cpan/Pod-Simple/t/search29.t',
    '../cpan/Pod-Simple/t/search60.t',
    
    '../cpan/Scalar-List-Utils/t/uniqnum.t',
    
    '../dist/PathTools/t/cwd.t',
    '../dist/PathTools/t/abs2rel.t',
    '../dist/PathTools/t/taint.t',
    
    '../dist/Carp/t/stack_after_err.t',
    
    '../dist/Storable/t/file_magic.t',
    '../dist/Storable/t/malice.t',

    '../dist/threads/t/kill3.t',
    
    '../ext/File-Find/t/taint.t',
    '../ext/File-Glob/t/basic.t',
    '../ext/File-Glob/t/threads.t',

    '../ext/XS-APItest/t/join_with_space.t',
    '../ext/XS-APItest/t/keyword_multiline.t',
    '../ext/XS-APItest/t/keyword_plugin.t',
    '../ext/XS-APItest/t/loopblock.t',
    '../ext/XS-APItest/t/newDEFSVOP.t',
    '../ext/XS-APItest/t/scopelessblock.t',
    '../ext/XS-APItest/t/stmtasexpr.t',
    '../ext/XS-APItest/t/stmtsasexpr.t',
    '../ext/XS-APItest/t/stuff_modify_bug.t',
    '../ext/XS-APItest/t/stuff_svcur_bug.t',
    '../ext/XS-APItest/t/subsignature.t',
    '../ext/XS-APItest/t/swaplabel.t',
    '../ext/XS-APItest/t/swaptwostmts.t',
    '../ext/XS-APItest/t/synthetic_scope.t',

    '../lib/perl5db.t',
);

sub dump_list {
    my @tests = @_;
    foreach my $t(@tests) {
        print "$t\n";
    }
}

sub exclude_tests {
    my @tests = @_;
    for my $black_list (@ios_blacklist)
    {
        for (my $index = 0; $index < scalar @tests;  $index ++)
        {
            if ($tests[$index] =~ m!$black_list!)
            {
                print "# iOS: excluding test: $tests[$index]\n";
                splice(@tests, $index, 1);
            }
        }
    }

    if ($Config{archname} =~ /x86_64/) {
        print "# NOTE: the following tests pass on device but fail on simulator. #TODO\n";
        for my $simul_black_list (@simul_blacklist)
        {
            for (my $index = 0; $index < scalar @tests;  $index ++)
            {
                if ($tests[$index] =~ m!$simul_black_list!)
                {
                    print "# iOS: excluding test: $tests[$index]\n";
                    splice(@tests, $index, 1);
                }
            }
        }
        @tests = grep(/^(?:(?!\.\.\/ext\/Pod\-Html))/, @tests);
    }

    # TODO. Device w/ make for CPAN installations that do not require cc
    @tests = grep(/^(?:(?!\.\.\/cpan\/ExtUtils\-MakeMaker))/, @tests);
    @tests = grep(/^(?:(?!\.\.\/cpan\/ExtUtils\-Install))/, @tests);
    @tests = grep(/^(?:(?!\.\.\/cpan\/Test\-Harness))/, @tests);
    @tests = grep(/^(?:(?!\.\.\/dist\/ExtUtils\-CBuilder))/, @tests);
    @tests = grep(/^(?:(?!\.\.\/dist\/ExtUtils\-ParseXS))/, @tests);
};

do './harness';
